name: Testing CI

on:
  push:
    branches:
      - master
      tags:
        - 'v*'
  workflow_dispatch:
    schedule:
      -cron: '0 1 * * *'

jobs:

  local_test_job:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Print Java version
        run: javac -version
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path:
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFile('**/*.gradle*) }}
          restore-keys:
            ${{ runner.os }}-gradle-

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'



  build_job:
    name: Building the APK
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path:
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFile('**/*.gradle*) }}
          restore-keys:
            ${{ runner.os }}-gradle-
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk

